#!/usr/bin/env bun
import { mkdir, readFile, writeFile } from "node:fs/promises"
import { dirname, relative, resolve, sep } from "node:path"
import { fileURLToPath } from "node:url"

const API_ROOT = resolve(fileURLToPath(import.meta.url), "..")
const ROUTES_DIR = resolve(API_ROOT, "routes")
const OUT_FILE = resolve(API_ROOT, "router.ts")

const isWatch = process.argv.includes("--watch")

type RouteEntry = {
  fileRelFromApiRoot: string
  importPath: string
  routePath: string
  varName: string
}

const toRoutePath = (fileRelFromRoutesDir: string) => {
  const noExt = fileRelFromRoutesDir.replace(/\.tsx?$/, "")
  const parts = noExt.split(sep)

  // Single-name convention: routes/**/route.ts
  // The filename itself is never part of the URL.
  if (parts.at(-1) === "route") parts.pop()

  const mapped = parts
    .flatMap((p) => {
      const catchAll = p.match(/^\[\.\.\.(.+)\]$/)
      if (catchAll) return [`:${catchAll[1]}*`]

      const param = p.match(/^\[(.+)\]$/)
      if (param) return [`:${param[1]}`]

      return [p]
    })
    .join("/")

  return mapped ? "/" + mapped : "/"
}

const sanitizeVar = (s: string) =>
  "r_" +
  s
    .replace(/\.tsx?$/, "")
    .replace(/[^a-zA-Z0-9_]+/g, "_")
    .replace(/^_+/, "")

const main = async () => {
  await mkdir(ROUTES_DIR, { recursive: true })

  const files: string[] = []
  for await (const file of new Bun.Glob("routes/**/*.{ts,tsx}").scan({ cwd: API_ROOT })) {
    if (file.endsWith(".d.ts")) continue
    // Routable modules are named exactly `route.ts`
    if (!file.endsWith("/route.ts") && !file.endsWith("/route.tsx")) continue
    files.push(file)
  }

  files.sort()

  const entries: RouteEntry[] = files.map((fileRelFromApiRoot) => {
    const fileRelFromRoutesDir = relative("routes", fileRelFromApiRoot)
    const importPath = "./" + fileRelFromApiRoot.replace(/\.tsx?$/, "")
    return {
      fileRelFromApiRoot,
      importPath,
      routePath: toRoutePath(fileRelFromRoutesDir),
      varName: sanitizeVar(fileRelFromApiRoot),
    }
  })

  const lines: string[] = []
  lines.push("/* eslint-disable */")
  lines.push("// This file is generated by scripts/routes.ts")
  lines.push('import type { Elysia } from "elysia"')
  lines.push("")

  for (const e of entries) {
    lines.push(`import * as ${e.varName} from "${e.importPath}"`)
  }

  lines.push("")
  lines.push("type RouteModule = Record<string, any>")
  lines.push("")
  lines.push("const registerMethods = (app: Elysia, path: string, mod: RouteModule) => {")
  lines.push('  if (typeof mod.GET === "function") app.get(path, mod.GET)')
  lines.push('  if (typeof mod.POST === "function") app.post(path, mod.POST)')
  lines.push('  if (typeof mod.PUT === "function") app.put(path, mod.PUT)')
  lines.push('  if (typeof mod.PATCH === "function") app.patch(path, mod.PATCH)')
  lines.push('  if (typeof mod.DELETE === "function") app.delete(path, mod.DELETE)')
  lines.push('  if (typeof mod.HEAD === "function") app.head(path, mod.HEAD)')
  lines.push('  if (typeof mod.OPTIONS === "function") app.options(path, mod.OPTIONS)')
  lines.push("}")
  lines.push("")
  lines.push("export const registerFileRoutes = (app: Elysia) => {")
  lines.push("  const routes: Array<[string, RouteModule]> = [")
  for (const e of entries) {
    lines.push(`    [${JSON.stringify(e.routePath)}, ${e.varName}],`)
  }
  lines.push("  ]")
  lines.push("")
  lines.push("  for (const [path, mod] of routes) {")
  lines.push("    registerMethods(app, path, mod)")
  lines.push("  }")
  lines.push("}")
  lines.push("")

  const next = lines.join("\n") + "\n"
  let prev: string | null = null
  try {
    prev = await readFile(OUT_FILE, "utf8")
  } catch {
    // ignore
  }

  if (prev !== next) {
    await mkdir(dirname(OUT_FILE), { recursive: true })
    await writeFile(OUT_FILE, next, "utf8")
  }

  console.log(`Generated ${relative(API_ROOT, OUT_FILE)} with ${entries.length} route file(s)`) 
}

await main()

if (isWatch) {
  console.log(`Watching ${relative(API_ROOT, ROUTES_DIR)} for changes...`)
  const interval = setInterval(() => {
    void main()
  }, 250)

  process.on("SIGINT", () => {
    clearInterval(interval)
    process.exit(0)
  })
}
