/* eslint-disable */
// This file is generated by scripts/routes.ts
import type { Elysia } from "elysia"


type RouteModule = Record<string, any>

const registerMethods = (app: Elysia, path: string, mod: RouteModule) => {
  if (typeof mod.GET === "function") app.get(path, mod.GET)
  if (typeof mod.POST === "function") app.post(path, mod.POST)
  if (typeof mod.PUT === "function") app.put(path, mod.PUT)
  if (typeof mod.PATCH === "function") app.patch(path, mod.PATCH)
  if (typeof mod.DELETE === "function") app.delete(path, mod.DELETE)
  if (typeof mod.HEAD === "function") app.head(path, mod.HEAD)
  if (typeof mod.OPTIONS === "function") app.options(path, mod.OPTIONS)
}

export const registerFileRoutes = (app: Elysia) => {
  const routes: Array<[string, RouteModule]> = [
  ]

  for (const [path, mod] of routes) {
    registerMethods(app, path, mod)
  }
}

